/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ThreadIdRouteImport } from './routes/$threadId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareSharedChatIdRouteImport } from './routes/share.$sharedChatId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadIdRoute = ThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSharedChatIdRoute = ShareSharedChatIdRouteImport.update({
  id: '/share/$sharedChatId',
  path: '/share/$sharedChatId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/sign-in': typeof SignInRoute
  '/share/$sharedChatId': typeof ShareSharedChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/sign-in': typeof SignInRoute
  '/share/$sharedChatId': typeof ShareSharedChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$threadId': typeof ThreadIdRoute
  '/sign-in': typeof SignInRoute
  '/share/$sharedChatId': typeof ShareSharedChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$threadId' | '/sign-in' | '/share/$sharedChatId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$threadId' | '/sign-in' | '/share/$sharedChatId'
  id: '__root__' | '/' | '/$threadId' | '/sign-in' | '/share/$sharedChatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreadIdRoute: typeof ThreadIdRoute
  SignInRoute: typeof SignInRoute
  ShareSharedChatIdRoute: typeof ShareSharedChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$threadId': {
      id: '/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$sharedChatId': {
      id: '/share/$sharedChatId'
      path: '/share/$sharedChatId'
      fullPath: '/share/$sharedChatId'
      preLoaderRoute: typeof ShareSharedChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreadIdRoute: ThreadIdRoute,
  SignInRoute: SignInRoute,
  ShareSharedChatIdRoute: ShareSharedChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
